#!/bin/bash

# TODO: Currently, this is hardcoded. Ideally, this should be rewritten to be configurable.

function ps1_powerline {
  RETCODE=$? # save return code
  NUM_JOBS=$(jobs -rp | wc -l)
  GIT_BRANCH=$(__git_ps1)

  local BOLD="\[\e[1;44;37m\]"

  local GREY="\[\e[5;40;37m\]"
  local GREY_END="\[\e[1;42;30m\]"

  local GREEN="\[\e[2;42;30m\]"
  local GREEN_END="\[\e[1;44;32m\]"

  local ORANGE="\[\e[5;43;30m\]"
  local ORANGE_END="\[\e[48;5;236m\]\[\e[38;5;208m\]"
  local ORANGE_RET_END="\[\e[48;5;160m\]\[\e[38;5;208m\]" # when next segment is prompt with return code

  local BLUE="\[\e[5;44;37m\]"
  local BLUE_END="\[\e[5;43;34m\]"           # when next segment is git
  local BLUE_END_JOBS="\[\e[48;5;93m\]\[\e[38;5;27m\]"       # when next segment is jobs
  local BLUE_END_ALT="\[\e[5;49;34m\]"       # when next segment is prompt
  local BLUE_END_RET="\[\e[5;41;34m\]"       # when next segment is prompt with return code

  local JOBS="\[\e[48;5;93m\]\[\e[38;5;255m\] ⏎"
  local JOBS_END="\[\e[48;5;236m\]\[\e[38;5;93m\]"           # when next segment is prompt
  local JOBS_NO_RET_END="\[\e[48;5;208m\]\[\e[38;5;93m\]"    # when next segment is git
  local JOBS_NO_GIT_END="\[\e[48;5;160m\]\[\e[38;5;93m\]"    # when next segment is prompt with return code

  local RET="\[\e[5;41;37m\]"
  local RET_END="\[\e[0m\]\[\e[1;100;31m\]\[\e[0m\] "

  local PROMPT="\[\e[5;49;37m\]"
  local PROMPT_END="\[\e[0m\]\[\e[1;103;30m\]\[\e[0m\] "

  if [ ! -w "$PWD" ]; then
    # Current directory is not writable
    BLUE_END="\[\e[48;5;160m\]\[\e[38;5;27m\]\[\e[38;5;255m\]  \[\e[48;5;208m\]\[\e[38;5;160m\]"
    BLUE_END_JOBS="\[\e[48;5;160m\]\[\e[38;5;27m\]\[\e[38;5;255m\]  \[\e[48;5;93m\]\[\e[38;5;160m\]"
    BLUE_END_ALT="\[\e[48;5;160m\]\[\e[38;5;27m\]\[\e[38;5;255m\]  \[\e[48;5;236m\]\[\e[38;5;160m\]"
    BLUE_END_RET="\[\e[48;5;160m\]\[\e[38;5;27m\]\[\e[38;5;255m\]  "
  fi

  # PREFIX="$GREY \t $GREY_END$GREEN @\h $GREEN_END"
  PREFIX="$BOLD"

  if [ -z "$GIT_BRANCH" ]; then
    # Is not a git repo
    if [ "$RETCODE" -eq 0 ]; then
      if [ "$NUM_JOBS" -eq 0 ]; then
        # No jobs or ret code
        PS1="$PREFIX$BLUE \W $BLUE_END_ALT$PROMPT \$ $PROMPT_END"
      else
        # no ret code but jobs
        PS1="$PREFIX$BLUE \W $BLUE_END_JOBS$JOBS$NUM_JOBS $JOBS_END$PROMPT \$ $PROMPT_END"
      fi
    else
      if [ "$NUM_JOBS" -eq 0 ]; then
        # No jobs but ret code is there
        PS1="$PREFIX$BLUE \W $BLUE_END_RET$RET \$ ⚑ $RETCODE $RET_END"
      else
        # Both jobs and ret code
        PS1="$PREFIX$BLUE \W $BLUE_END_JOBS$JOBS$NUM_JOBS $JOBS_NO_GIT_END$RET \$ ⚑ $RETCODE $RET_END"
      fi
    fi
  else
    # Is a git repo
    local NUM_MODIFIED=$(git diff --name-only --diff-filter=M | wc -l)
    local NUM_STAGED=$(git diff --staged --name-only --diff-filter=AM | wc -l)
    local NUM_CONFLICT=$(git diff --name-only --diff-filter=U | wc -l)
    local GIT_STATUS="\[\e[1;47;33m\]\[\e[5;47;34m\] ✚$NUM_MODIFIED \[\e[0m\]\[\e[5;47;30m\]\[\e[5;47;32m\] ✔$NUM_STAGED \[\e[5;47;30m\]\[\e[5;47;31m\] ✘$NUM_CONFLICT $BOLD"
    if [ "$RETCODE" -eq 0 ]; then
      GIT_STATUS+="\[\e[5;40;37m\]"
    else
      GIT_STATUS+="\[\e[1;41;37m\]"
    fi

    if [ "$RETCODE" -eq 0 ]; then
      if [ "$NUM_JOBS" -eq 0 ]; then
        # No jobs or ret code
        PS1="$PREFIX$BLUE \W $BLUE_END$ORANGE $GIT_BRANCH $GIT_STATUS$PROMPT \$ $PROMPT_END"
      else
        # no ret code but jobs
        PS1="$PREFIX$BLUE \W $BLUE_END_JOBS$JOBS$NUM_JOBS $JOBS_NO_RET_END$ORANGE $GIT_BRANCH $GIT_STATUS$PROMPT \$ $PROMPT_END"
      fi
    else
      if [ "$NUM_JOBS" -eq 0 ]; then
        # No jobs but ret code is there
        PS1="$PREFIX$BLUE \W $BLUE_END$ORANGE $GIT_BRANCH $GIT_STATUS$RET \$ ⚑ $RETCODE $RET_END"
      else
        # Both jobs and ret code
        PS1="$PREFIX$BLUE \W $BLUE_END_JOBS$JOBS$NUM_JOBS $JOBS_NO_RET_END$ORANGE $GIT_BRANCH $GIT_STATUS$RET \$ ⚑ $RETCODE $RET_END"
      fi
    fi

  fi
}

if [  "$TERM" != "linux" ]; then
   # PROMPT_COMMAND="ps1_powerline; $PROMPT_COMMAND"
   PROMPT_COMMAND="ps1_powerline;"
fi
